name: flutter_application_1
description: A new Flutter project

publish_to: 'none' # kalau tidak publish ke pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  getwidget: ^7.0.0
  shared_preferences: ^2.5.3
  device_info_plus: ^12.1.0
  webview_flutter: ^4.13.0
  intl: ^0.20.2
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.jpeg
